### ISSUE TITLE
Where do I get "Brief.exe"?

### ISSUE THREAD

**Issue by znmeb** [AshleyF/BriefEmbedded#10]
The documentation at https://github.com/AshleyF/BriefEmbedded/blob/master/extras/Documents/README.md#interactive-console refers to a program called "Brief.exe"

"Once the firmware has been flashed, launch Brief.exe. This is an interactive console giving you full control of the MCU. It can be used to experiment with and to even program it."

Where do I get `Brief.exe` and is it available on both Windows and Linux?

**Comment by AshleyF** [comment]
The documentation seems to be outdated. The interactive is actually called `Interactive.exe`

I just updated the doc to say, "...launch `Interactive.exe`, which is [built from this project](https://github.com/AshleyF/BriefEmbedded/tree/master/extras/Interactive). It is a .NET Core app and works on Linux, macOS and Windows."

Hope that helps!

**Comment by znmeb** [comment]
@AshleyF Thanks! Is that downloadable or do I need to build it? If I need to build it, is VSCode enough or do I need Visual Studio?

**Comment by AshleyF** [comment]
You can build at the command line with `dotnet build extras/Interactive` (with .NET SDK 3.1 installed) and then run with `dotnet extras/Interactive/bin/Debug/netcoreapp3.1/Interactive.dll`. Or, actually you can build and run in one shot with simply `dotnet run extras/Interactive`.

Hope that helps!
